import { IoIosSunny, IoIosMoon } from "react-icons/io";
import {
  FaPaperclip,
  FaPaperPlane,
  FaRegImage,
  FaRobot,
  FaUser,
  FaWifi,
  FaRegUser,
  FaPhone,
  FaRegCheckCircle,
  FaFacebook,
  FaInfoCircle,
  FaCreditCard,
  FaExclamationTriangle,
  FaUserShield,
  FaSyncAlt,
  FaPhoneAlt,
  FaStar,
  FaCalendarAlt,
  FaTimes,
  FaChevronDown,
  FaChevronUp,
  FaQuestionCircle,
  FaMapMarkerAlt,
  FaUsers,
  FaShieldAlt,
} from "react-icons/fa";
import { FaLocationDot, FaArrowRightLong } from "react-icons/fa6";
import { CiSearch, CiLocationOn } from "react-icons/ci";

import { IoLocationOutline } from "react-icons/io5";
import {
  MdFastfood,
  MdOutlineHotel,
  MdFlight,
  MdFavorite,
  MdOutlineStarPurple500,
  MdEmail,
  MdLocationOn,
  MdAccessTime,
  MdAttachMoney,
} from "react-icons/md";
import { FiMenu, FiX, FiClock, FiChevronDown, FiFilter } from "react-icons/fi";
import { AiOutlineRight, AiOutlineLeft } from "react-icons/ai";
const icons = {
  IoIosSunny,
  IoIosMoon,
  FaPaperclip,
  FaPaperPlane,
  FaRegImage,
  FaRobot,
  FaUser,
  MdFastfood,
  MdOutlineHotel,
  MdFlight,
  FaWifi,
  FiMenu,
  FiX,
  CiSearch,
  FiClock,
  FaRegUser,
  MdFavorite,
  IoLocationOutline,
  AiOutlineRight,
  MdOutlineStarPurple500,
  CiLocationOn,
  FaPhone,
  MdEmail,
  FaLocationDot,
  FiChevronDown,
  MdLocationOn,
  MdAccessTime,
  MdAttachMoney,
  FaArrowRightLong,
  FaRegCheckCircle,
  FaFacebook,
  FaInfoCircle,
  FaCreditCard,
  FaExclamationTriangle,
  FaUserShield,
  FaSyncAlt,
  FaPhoneAlt,
  FaStar,
  FaCalendarAlt,
  FaTimes,
  FaChevronDown,
  FaChevronUp,
  FiFilter,
  FaQuestionCircle,
  FaMapMarkerAlt,
  FaUsers,
  FaShieldAlt,
  AiOutlineLeft,
};
export default icons;
