import { IoIosSunny, IoIosMoon } from "react-icons/io";
import {
  FaPaperclip,
  FaPaperPlane,
  FaRegImage,
  FaRobot,
  FaUser,
  FaWifi,
  FaRegUser,
  FaPhone,
  FaRegCheckCircle,
  FaFacebook,
  FaInfoCircle,
  FaCreditCard,
  FaExclamationTriangle,
  FaUserShield,
  FaSyncAlt,
  FaPhoneAlt,
} from "react-icons/fa";
import { FaLocationDot, FaArrowRightLong } from "react-icons/fa6";
import { CiSearch, CiLocationOn } from "react-icons/ci";
import { AiOutlineRight } from "react-icons/ai";
import { IoLocationOutline } from "react-icons/io5";
import {
  MdFastfood,
  MdOutlineHotel,
  MdFlight,
  MdFavorite,
  MdOutlineStarPurple500,
  MdEmail,
  MdLocationOn,
  MdAccessTime,
  MdAttachMoney,
} from "react-icons/md";
import { FiMenu, FiX, FiClock, FiChevronDown } from "react-icons/fi";
const icons = {
  IoIosSunny,
  IoIosMoon,
  FaPaperclip,
  FaPaperPlane,
  FaRegImage,
  FaRobot,
  FaUser,
  MdFastfood,
  MdOutlineHotel,
  MdFlight,
  FaWifi,
  FiMenu,
  FiX,
  CiSearch,
  FiClock,
  FaRegUser,
  MdFavorite,
  IoLocationOutline,
  AiOutlineRight,
  MdOutlineStarPurple500,
  CiLocationOn,
  FaPhone,
  MdEmail,
  FaLocationDot,
  FiChevronDown,
  MdLocationOn,
  MdAccessTime,
  MdAttachMoney,
  FaArrowRightLong,
  FaRegCheckCircle,
  FaFacebook,
  FaInfoCircle,
  FaCreditCard,
  FaExclamationTriangle,
  FaUserShield,
  FaSyncAlt,
  FaPhoneAlt,
};
export default icons;
