import { IoIosSunny, IoIosMoon } from "react-icons/io";
import { RiLockPasswordFill } from "react-icons/ri";
import {
  FaPaperclip,
  FaPaperPlane,
  FaRegImage,
  FaRobot,
  FaUser,
  FaWifi,
  FaRegUser,
  FaPhone,
  FaRegCheckCircle,
  FaFacebook,
  FaInfoCircle,
  FaCreditCard,
  FaExclamationTriangle,
  FaUserShield,
  FaSyncAlt,
  FaPhoneAlt,
  FaStar,
  FaCalendarAlt,
  FaTimes,
  FaChevronDown,
  FaChevronUp,
  FaQuestionCircle,
  FaMapMarkerAlt,
  FaUsers,
  FaShieldAlt,
  FaCheck,
  FaUserAlt,
  FaEllipsisV,
  FaTag,
  FaEye,
  FaEyeSlash,
} from "react-icons/fa";
import { FcGoogle } from "react-icons/fc";
import { FaLocationDot, FaArrowRightLong } from "react-icons/fa6";
import { CiSearch, CiLocationOn } from "react-icons/ci";
import { FiPhoneCall } from "react-icons/fi";
import { IoLocationOutline, IoCloseSharp } from "react-icons/io5";
import {
  MdFastfood,
  MdOutlineHotel,
  MdFlight,
  MdFavorite,
  MdOutlineStarPurple500,
  MdEmail,
  MdLocationOn,
  MdAccessTime,
  MdAttachMoney,
} from "react-icons/md";
import {
  FiMenu,
  FiX,
  FiClock,
  FiChevronDown,
  FiFilter,
  FiArrowUpRight,
} from "react-icons/fi";
import { AiOutlineRight, AiOutlineLeft } from "react-icons/ai";
import { CiShare1 } from "react-icons/ci";

const icons = {
  IoIosSunny,
  IoIosMoon,
  FaPaperclip,
  FaPaperPlane,
  FaRegImage,
  FaRobot,
  FaUser,
  MdFastfood,
  MdOutlineHotel,
  MdFlight,
  FaWifi,
  FiMenu,
  FiX,
  CiSearch,
  FiClock,
  FaRegUser,
  MdFavorite,
  IoLocationOutline,
  AiOutlineRight,
  MdOutlineStarPurple500,
  CiLocationOn,
  FaPhone,
  MdEmail,
  FaLocationDot,
  FiChevronDown,
  MdLocationOn,
  MdAccessTime,
  MdAttachMoney,
  FaArrowRightLong,
  FaRegCheckCircle,
  FaFacebook,
  FaInfoCircle,
  FaCreditCard,
  FaExclamationTriangle,
  FaUserShield,
  FaSyncAlt,
  FaPhoneAlt,
  FaStar,
  FaCalendarAlt,
  FaTimes,
  FaChevronDown,
  FaChevronUp,
  FiFilter,
  FaQuestionCircle,
  FaMapMarkerAlt,
  FaUsers,
  FaShieldAlt,
  AiOutlineLeft,
  CiShare1,
  FaCheck,
  IoCloseSharp,
  FiPhoneCall,
  FaUserAlt,
  FaEllipsisV,
  FiArrowUpRight,
  FaTag,
  RiLockPasswordFill,
  FcGoogle,
  FaEye,
  FaEyeSlash,
};
export default icons;
